import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/componnets/NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "System OS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="Pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
